"""Compatibility exports for domain models.

New application code imports from ``retail_agent.domain.models`` directly.
"""

from retail_agent.domain.models import (
    AgentFailure,
    AnalysisReport,
    AnalysisResponse,
    AnalysisResult,
    ChartArtifact,
    ChartFormat,
    ChartRequest,
    ClarificationRequest,
    ContextualizedQuestion,
    Conversation,
    ConversationId,
    ConversationRole,
    ConversationTurn,
    DataAnalysisResult,
    ExecutionFailure,
    FailureCode,
    GoldenExample,
    GoldenTrio,
    QueryResult,
    RetrievedTrio,
    SafeSql,
    SchemaExplanationResult,
    ToolResultSummary,
    UnsupportedRequest,
    UserPreferences,
    UserProfile,
    UserQuestion,
)

__all__ = [
    "AgentFailure",
    "AnalysisResult",
    "AnalysisReport",
    "AnalysisResponse",
    "ChartArtifact",
    "ChartFormat",
    "ChartRequest",
    "ClarificationRequest",
    "ContextualizedQuestion",
    "Conversation",
    "ConversationId",
    "ConversationRole",
    "ConversationTurn",
    "FailureCode",
    "DataAnalysisResult",
    "ExecutionFailure",
    "GoldenExample",
    "GoldenTrio",
    "QueryResult",
    "RetrievedTrio",
    "SafeSql",
    "SchemaExplanationResult",
    "ToolResultSummary",
    "UserPreferences",
    "UserProfile",
    "UserQuestion",
    "UnsupportedRequest",
]
